# Business Understanding

## Business objectives


:::{style="color: blue;"}
*What is the company wishing to achieve?*
:::

A Luxury high end Brand sells its goods online using its own e-commerce platform and wishes to **increase its conversion rate**.

No further information is available about the companies business like other sale channel or product category, although from the available information we can conclude the brand has a global reach.

```{r Conversion rate, echo=FALSE, message=TRUE, warning=FALSE}
source("scripts/eda_functions.r")
data <- read.csv("data/train_full.csv")

ggplot(data, aes(x = factor(bought), 
                 y = prop.table(stat(count)), 
                 label = scales::percent(prop.table(stat(count))) )) +
    geom_bar(fill="darkblue", color="black") +
    geom_text(stat = 'count',
                position = position_dodge(.9), 
                vjust = -0.5, 
                size = 3) +
    scale_y_continuous(labels = scales::percent) +
    theme_masterDS() +
    labs(
      x = "",
      y = "",
      title = "Conversion Rate",
      caption = "Calculation based on data set train-full"
    ) 

```

The available sample data shows a 8% top of funnel conversion rate ( substantially higher than e-commerce benchmark which is around 2% ). Conversion top of funnel uses landing touchpoints as index. No information is given about any goal or additional metrics tracked by the company, therefore it won't be take into consideration during this project.


## Assess Situation

:::{style="color: blue;"}
*What is available for the project?*
:::

A sample of balanced and unbalanced information was made available containing information about individual sessions. No information is provided about session definitions (eg: cap session duration. Industries norm is between 25 ~ 30 min) and about user anonymous ids. There isn't therefore, enough information to analyse potential impacts of different customer journeys. Additionally no information is provided concerning the date each session accured, which invalidate any seasonal analysis.

Given the generaly accepted impact that multitudinous has on conversion it will be assume henceforward that **sessions are independent and identically distributed**

### Hardware and environment special needs

There aren't any specific needs for hardware or data infrastructure. Data will be ingested directly from csv files and all transformation will be done on development machine. Environment information available on `.renv` file

## Data Mining Goals

:::{style="color: blue;"}
*How will Data team achieve Business Goals?*
:::

Based on the available information the project is **binary classification problem with a focus on inference.**. The company is looking to identify session variables which signal users which will convert or not in order to redefine marketing strategies and approaches. There are only to available states, either the user "bought" or it didn't. 

No information is provide regarding the expected use of this project. Therefore it will be assumed through this project that the main stakeholders is the marketing team and are human. Therefore, a bigger focus on the modeling process and coefficients is needed and is considered part of the deliver. The assumption is relevant since it impacts the final conclusions and the final model chosen. Given 2 similar models with sensible the same target metric the more interpretable one will be chosen.

:::{.title}
**Target metrics**
:::

Given the goals of this project stated before on Business Objectives the focus will be on maximizing *Accuracy*. The business is looking for the model which more accurately explains session conversion.

:::{.title}
**Data questions**
:::

During this project the following questions will be addressed

- Is there a relationship between a conversion and information available related to that session ?
- Which is the contribution of each of the variables to conversion?
- How accurately can we estimate the effect on conversion?
- Is there synergy among each session elements?
- Does a model surpass a naive baseline approach of assuming the most shown class?
- Does Data imbalance impact output?

## Project Plan

Due to time restrictions the present project follows a hybrid approach of CRISP-DM and TDSF and is organized in the following stages:

Stage 1 - Understand Business and Its environment

Stage 2 - Understand and explore data: study of distribution and relationship among available data

Stage 3 - Data preparation for modeling: Preprocessing workflow

Stage 4 - Modeling: Model definition, initial experiments and hyperparameter tunning

Stage 5 - Delivery: Conclusions of the project

## Terms

The following terms will be used during this project with the following meaning:

**User:** any unique IP which has reached the store. One individual can have more than one ip,

**Client:** a user that converted, this means, it bought from the shop,

**Touchpoints:** represents any interaction between the user and the online store of any sort,

**Session:** a period of time (normally of 30 min max) during which the user interacted with the shop. Every session starts with a touchpoint. Under some conditions depending on the website metrics collection a session can have more than one touchpoint. 
