---
title: "R Notebook"
output: html_notebook
---

## Support Vector Machine

```{r , include=FALSE}
# libraries
library(tidyverse)
library(tidymodels)
library(workflowsets)

source("scripts/eda_functions.r")

doParallel::registerDoParallel()

```

```{r , message=TRUE, warning=FALSE, include=FALSE}
# import data and prepocess

# import and prepare data
# import data
unbalanced_data <- read_csv("./data/train_full.csv") %>% 
  dplyr::select(-...1, -session_id) %>% 
  dplyr::mutate(bought = as.factor(bought))
balanced_data <- read_csv("./data/train_balanced.csv") %>% 
  dplyr::select(-...1, -session_id) %>% 
  dplyr::mutate(bought = as.factor(bought))

# script with visual functions
source("scripts/eda_functions.r")


```

```{r, message=TRUE, warning=FALSE, include=FALSE}

# cv 10 folds

set.seed(1234)
# To keep speed of processing no repeats will be used during resampling
# folds <- vfold_cv(balanced_data, v = 10, repeats = 5)

folds <- vfold_cv(balanced_data, v = 10)

```

### Initial experience: Linear Kernel

A Linear Kernel with default parameters will be used as the basis for

```{r }
# 1. specify the model
svm_linear <-
  svm_linear(cost = 0.5) %>% 
  set_engine("kernlab") %>% 
  set_mode("classification")


# 2. preprocessing 
preprocess <- 
  recipe(bought ~ . , data = balanced_data) %>%
  step_ratio(starts_with("unique_"), denom = denom_vars(view_qty)) %>% 
  step_rm(device_group, unique_product_qty, unique_browse_designer_qty, 
          unique_browse_category_qty) %>% 
  step_other(country, browser_name, threshold = 0.05) %>% 
  step_log(view_qty) %>%
  step_filter(
    duration < 60 * 60 * 24,
    !((view_qty <= 1) & (duration <= 2))
    ) %>%
  step_string2factor(all_nominal_predictors()) %>% 
  step_impute_knn(all_predictors(), neighbors = 3) %>%
  step_pca(starts_with("has_"), num_comp = 1) %>% 
  step_corr(all_numeric_predictors(), threshold = .5) 
  

preprocess_mlp_svm <- 
  preprocess %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_scale(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_zv(all_predictors()) 

# 3, Buildworkflow
svm_linear_wflow <- 
  workflow() %>% 
  add_model(svm_linear) %>% 
  add_recipe(preprocess_mlp_svm)

#4. Fit model
fit_control <- control_grid(save_pred = TRUE, save_workflow = TRUE)

svm_linear_fit <- 
  svm_linear_wflow %>% 
  fit_resamples(
    resamples = folds, 
    verbose = TRUE, 
    metrics = metric_set(yardstick::roc_auc, yardstick::accuracy, yardstick::sens,yardstick::specificity),
    control = fit_control)


#5. Performance metrics over the validation set
collect_metrics(svm_linear_fit)

```

```{r}

conf_mat_resampled(svm_linear_fit)

```

```{r }

svm_linear_fit %>% 
  collect_predictions() %>% 
  group_by(id) %>% 
  roc_curve(bought, .pred_0) %>% 
  ggplot(aes(1- specificity, sensitivity, color = id)) +
  geom_abline(lty = 3, color = "gray80", size = 1) +
  geom_path(show.legend = FALSE, alpha = 0.6, size = 1) +
  theme_masterDS() +
  coord_equal()

```



### Fitting multiple models

```{r }

#1. list model to inject into workflow
svm_linear <-
  svm_rbf(cost = tune()) %>% 
  set_engine("kernlab") %>% 
  set_mode("classification")

svm_poly_kernlab_spec <-
  svm_poly(cost = tune(), degree = tune(), scale_factor = tune(), margin = tune()) %>%
  set_engine('kernlab') %>%
  set_mode('classification')

svm_rbf_kernlab_spec <-
  svm_rbf(cost = tune(), rbf_sigma = tune(), margin = tune()) %>%
  set_engine('kernlab') %>%
  set_mode('classification')

models_flow <- 
  workflow_set(
    preproc = list(recipe = preprocess_mlp_svm),
    models = list(svm_ploy = svm_poly_kernlab_spec, svm_rbf = svm_rbf_kernlab_spec, linear = svm_linear),
    cross = TRUE 
    )

```

```{r}

svm_wf_fit <- 
  models_flow %>%
  workflow_map(
    fn ="tune_grid",
    resamples = folds,
    grid = 5,
    metrics = metric_set(yardstick::roc_auc, yardstick::accuracy, yardstick::sens, yardstick::spec),
    verbose = TRUE
    ) 

```

```{r}

autoplot(svm_wf_fit) +
  theme_masterDS()

```

```{r}
autoplot(svm_wf_fit, select_best = TRUE) +
  theme_masterDS()
```

```{r}
rank_results(svm_wf_fit, rank_metric = "sens", select_best = TRUE) 

```

```{r}

rank_results(svm_wf_fit, rank_metric = "accuracy", select_best = TRUE) 

```

```{r}

autoplot(svm_wf_fit, metric = "accuracy",id = "recipe_svm_ploy")

```


```{r}
# export files
save(svm_wf_fit,file="_models/svm_wf_fit.RData")
save(svm_linear_fit, file = "_models/svm_linear_fit.RData")
```

